### ISSUE TITLE
conflict with notmuch ?

### ISSUE THREAD

**Issue by pseudomyne** [thamer/diredful#1]
hi,
just installed diredful yesterday. i was so happy to find it, since i was looking for this kind of thing for long ! (dired-rainbow does not work on my config). alas, i get a very annoying thing : input fields in diredful-edit (or diredful-add) but also in M-x customize, become impractible in various ways. In diredful input fields, 'v' shows the version of my notmuch client ! And in M-x customize, input fields are not accessible at all.... D(i)redful ! 
(Removing diredful suppress the issue)....... any idea ? thank you

**Comment by thamer** [comment]
The only possible point of conflict I see is that both packages are using `custom-face-edit` (per [this thread](http://notmuch.198994.n3.nabble.com/PATCH-use-custom-face-edit-value-type-in-notmuch-search-line-faces-td2738205.html)). I remember seeing something similar, but I'm no longer able to reproduce it with my current config (using Emacs 24.5).

Which version of Emacs are you using? And if possible, could you test with `emacs -Q` and see if loading diredful.el before or after notmuch would solve this problem?

**Comment by thamer** [comment]
I'm now able to reproduce the "v" issue. Seems to be a bug in notmuch-hello.el, which modifies `widget-keymap`. I suggest that you file a bug with notmuch.

**Comment by pseudomyne** [comment]
Some notmuch developer (Mark Walters) has already patched notmuch-hello (see link below) and i personaly could apply the patch with limited success after some (guided) hack (limited to the eradication of the 'v' syndrome). Customization pages still bug hard (just as i mentioned above).

Here is how to reproduce the bug with emacs -q : load notmuch + load diredful, then  M-x diredful-edit (diredful-add if nothing to edit yet ?) then M-x customize and input fields _get unusable, like read-only._ 

I use emacs 24.4.1.
I've also tried your suggestion with emacs -q. Loading one before the other does not change anything. thank you anyway.
http://notmuch.198994.n3.nabble.com/PATCH-emacs-hello-fix-accidental-modification-of-widget-keymap-tc4034300.html

**Comment by thamer** [comment]
The issue of inaccessible edit fields should be fixed now (version 1.4). 

Thanks.

**Comment by pseudomyne** [comment]
everything seems fine now. many thanks !

**Comment by pseudomyne** [comment]
Hi Thamer,
I’m still happy with diredful, which made files easier to read for me. Since, i’m now looking for a way to make use of diredful with dired+, because I want to highlight and colour files sizes and times, something diredful seems not able to do.
I can’t achieve that. It seems it’s either one _or_ the other (diredful or diredp). Do you confirm ?
Do you want me to publish this question in your github page ?
many thanks,
xavier

**Comment by thamer** [comment]
Hi Xavier,

It depends on whether dired+ supports `dired-font-lock-keywords` (the default method for fontification provided by dired.el and used by diredful). 

AFAIK, dired+ uses its own custom fontification (see `diredp-font-lock-keywords-1`). It's probably overriding `dired-font-lock-keywords` and any settings added by diredful there.

Regards,

**Comment by pseudomyne** [comment]
Thamer,
thank you for replying. I’m afraid i don’t have enough lisp skills to fully understand your reply… All I can say is I had to put 
(setq font-lock-maximum-decoration (quote ((dired-mode) (t . t))))
to make direful work with dired+, and that, if I quote this piece of code, dired+ will «override» diredful.

best. xavier
